(() => {
  const $ = id => document.getElementById(id);
  const packSize=$('packSize'), packUnit=$('packUnit'), pc=$('pc'), pcWrap=$('pcWrap'), ea=$('ea');
  const seedType=$('seedType'), regularSample=$('regularSample'), rows=$('sampleRows'), noSamples=$('noSamples'), message=$('message');
  const num=el=>Number(el.value); const positive=el=>el.value!==''&&Number.isFinite(num(el))&&num(el)>0;
  const clear=()=>['total','kgEa','baseKg','overpackKg','regularKg','customKg'].forEach(id=>$(id).textContent='—');
  function kgFrom(weight,unit,seedPC){if(unit==='KG')return weight;if(unit==='G')return weight/1000;if(unit==='LB')return weight/2.2046;if(unit==='KS')return ((weight*1000)/seedPC)/2.2046;return 0}
  function updatePC(){const needed=['KS','MS'].includes(packUnit.value)||[...rows.querySelectorAll('.sample-unit')].some(x=>x.value==='KS');pcWrap.hidden=!needed}
  function addSample(){if(rows.children.length>=10)return;const row=document.createElement('div');row.className='sample-row';row.innerHTML=`<label>Quantity<input class="sample-qty" type="number" min="1" step="1" inputmode="numeric" placeholder="6"></label><label>Weight each<input class="sample-weight" type="number" min="0" step="any" inputmode="decimal" placeholder="1"></label><label>Unit<select class="sample-unit"><option>KG</option><option>G</option><option>LB</option><option>KS</option></select></label><button type="button" class="secondary remove">Remove</button>`;rows.appendChild(row);noSamples.hidden=true;row.querySelector('.remove').addEventListener('click',()=>{row.remove();noSamples.hidden=rows.children.length>0;updatePC();calculate()});row.querySelectorAll('input,select').forEach(x=>x.addEventListener('input',()=>{updatePC();calculate()}));calculate()}
  function calculate(){message.hidden=true;updatePC();if(!positive(packSize)||!positive(ea)){clear();return}const needsPC=!pcWrap.hidden;if(needsPC&&!positive(pc)){clear();message.textContent='Enter a valid Seed Count / PC to calculate seed-based quantities.';message.hidden=false;return}const size=num(packSize), count=num(pc), totalEA=num(ea);let kgEA=0;if(packUnit.value==='KG')kgEA=size;else if(packUnit.value==='LB')kgEA=size/2.2046;else if(packUnit.value==='KS')kgEA=((size*1000)/count)/2.2046;else if(packUnit.value==='MS')kgEA=((size*1000000)/count)/2.2046;if(!Number.isFinite(kgEA)||kgEA<=0){clear();return}const base=kgEA*totalEA;const overpack=base*(seedType.value==='commercial'?.01:.005);const regular=Number(regularSample.value);let custom=0,invalid=false;rows.querySelectorAll('.sample-row').forEach(row=>{const q=row.querySelector('.sample-qty'),w=row.querySelector('.sample-weight'),u=row.querySelector('.sample-unit').value;if(q.value===''&&w.value==='')return;if(!positive(q)||!positive(w)){invalid=true;return}custom+=num(q)*kgFrom(num(w),u,count)});if(invalid){message.textContent='Complete Quantity and Weight for each custom sample, or remove the unused row.';message.hidden=false}const raw=base+overpack+regular+custom;$('kgEa').textContent=kgEA.toFixed(4)+' kg';$('baseKg').textContent=base.toFixed(2)+' kg';$('overpackKg').textContent=overpack.toFixed(2)+' kg';$('regularKg').textContent=regular.toFixed(2)+' kg';$('customKg').textContent=custom.toFixed(2)+' kg';$('total').textContent=Math.ceil(raw).toLocaleString()+' KG'}
  $('addSample').addEventListener('click',addSample);[packSize,packUnit,pc,ea,seedType,regularSample].forEach(x=>x.addEventListener('input',calculate));$('reset').addEventListener('click',()=>{packSize.value='';packUnit.value='KS';pc.value='';ea.value='';seedType.value='commercial';regularSample.value='5';rows.innerHTML='';noSamples.hidden=false;message.hidden=true;updatePC();clear();packSize.focus()});updatePC();
})();
